### ISSUE TITLE
make clean 해결 안 됨

### ISSUE THREAD

**Issue by kkwakna** [DKU-EmbeddedSystem-Lab/2024_DKU_OS#10]
저도 run함수 실행 결과가 출력 되지 않아서 make clean후 make를 해봤는데 해결되지 않습니다. 
이런 경우엔 어떻게 해야 하나요?

**Comment by min-guk** [comment]
저희 연구실 ICT관 514호에 오시면, 학생분의 과제 실습 환경을 확인해드리도록 하겠습니다.
방문 가능한 날짜와 시간대 [mgchoi@dankook.ac.kr](mailto:mgchoi@dankook.ac.kr)로 알려주세요

**Comment by kkwakna** [comment]
해결했습니다. 감사합니다!
