### ISSUE TITLE
정답 처리 기준

### ISSUE THREAD

**Issue by lottoian** [DKU-EmbeddedSystem-Lab/2024_DKU_OS#12]
![스크린샷 2024-04-07 132246](https://github.com/DKU-EmbeddedSystem-Lab/2024_DKU_OS/assets/67960289/fc38087b-b8fc-4fbb-a8e9-32188ac396e9)

위 사진과 같이 SPN을 구현하고 make 후에 test를 수행한 결과입니다
해당 테스트는 SPN에서 workload A의 time_quantum 0.01때의 수행 결과입니다.
print_order()와 print_stat() 모두 원래 출력 해야하는 값과 동일하다고 생각하는데 hash value 검증하는 과정에서 어떤게 문제인지 4개의 test case중에 3개만 정답 처리되고 위 사진 하나만 failed처리가 되었습니다.

다른 분들과 의견 공유를 해봐도 어떤 점이 문제인지를 몰라 issue 올립니다.

감사합니다! 
![스크린샷 2024-04-07 132639](https://github.com/DKU-EmbeddedSystem-Lab/2024_DKU_OS/assets/67960289/131bfc96-857d-4282-96fe-12ec916b3e9d)

**Comment by min-guk** [comment]
채점은 end_jobs_ 벡터의 데이터 부분을 통째로 해시값으로 변환해서 비교합니다.
출력 부분이 정답과 일치하더라고, 출력 되지 않은 부분이 달라서 그러지 않을까 생각되네요.

계속해서 문제가 해결이 안되면, mgchoi@dankook.ac.kr로 코드와 실험 환경 보내주세요.

**Comment by min-guk** [comment]
추가로, 예제로 제공한 FCFS는 정상적으로 모든 CASE를 통과하는지 확인해보시면 좋을 것 같네요.

**Comment by min-guk** [comment]
double 자료형 연산으로 end_jobs에 저장된 계산 결과가 정답과 동일하지 않더라도, double 자료형 유효숫자보다 적게 차이가 난다면 정답 처리할 예정입니다.
