### ISSUE TITLE
queue make 오류

### ISSUE THREAD

**Issue by ysoh20** [DKU-EmbeddedSystem-Lab/2024_DKU_OS#13]
현재 queue를 make 하면 다음과 같은 오류가 발생합니다
![image](https://github.com/DKU-EmbeddedSystem-Lab/2024_DKU_OS/assets/149280122/1e3f047b-ec8e-45d1-bffe-38bfb68c3270)

**Comment by min-guk** [comment]
```c++
// test_util.cpp
#include <algorithm>
```
test_util.cpp 파일에 algorithm 라이브러리를 추가하면 됩니다.
혹은 과제 코드에도 반영하였으니, `git pull`하여 진행하시면 됩니다.

환경에 따라 명시적으로 참조하지 않아도 되는 경우가 있었네요.
