### ISSUE TITLE
test 채점 관련 질문

### ISSUE THREAD

**Issue by ssng131** [DKU-EmbeddedSystem-Lab/2024_DKU_OS#14]
![스크린샷 2024-05-07 221951](https://github.com/DKU-EmbeddedSystem-Lab/2024_DKU_OS/assets/151361819/9a994e10-e617-4be0-8e2e-2124017c6dea)

테스트를 할 때 Fine-grained Lock 부분에서 마지막의 insert, lookup, remove 모두 테스트하는 경우는 정답이 나오는데, 앞의 insert와 lookup부분만 정답과 오답이 매번 바뀌어 가며 출력됩니다. 마지막 테스트가 정답이 나온다는 건 앞의 insert와 lookup메소드가 문제없다는 뜻 같은데 이게 아닌가요?

**Comment by min-guk** [comment]
![image](https://github.com/DKU-EmbeddedSystem-Lab/2024_DKU_OS/assets/87025898/1f8a76e4-a62a-4ae7-ad73-771c7f085773)

1.
INSERT_LOOKUP은 Workload 시행 후 중위 순회하여, 트리의 구성이 올바른지 채점합니다.
INSERT_LOOKUP_DELETE는 Multi-thread인 경우, Workload 시행 후 중위 순회하지 않습니다.

2.
실행마다 정답여부가 매번 바뀐다는 것은 구현이 잘못된 것을 의미합니다.
운에 따라 Lock이 잘 잡히기도, 그렇지 않기도 한 것으로 보입니다.
