### ISSUE TITLE
제출파일 관련 질문

### ISSUE THREAD

**Issue by applebos** [DKU-EmbeddedSystem-Lab/2024_DKU_OS#15]
queue_impl.cpp_학번_이름.h 로 제출하면 파일의 확장명이 바뀌는데 .cpp파일도 .h파일로 바꿔서 전송해야 하나요?

**Comment by min-guk** [comment]
![image](https://github.com/DKU-EmbeddedSystem-Lab/2024_DKU_OS/assets/87025898/c0c89baa-ecfa-4e31-8510-b1068fea6396)

위와 같이 제출 파일명 형식을 수정하였으니, 참고 바랍니다.
알려줘서 고맙습니다.
