### ISSUE TITLE
제출일자 질문

### ISSUE THREAD

**Issue by Chang-EE** [DKU-EmbeddedSystem-Lab/2024_DKU_OS#17]
교수님께서 예비군 일정 고려해주신다고 14일 24시까지로 정정해주셨는데,
pdf에는 반영이 안된 것 같아서 확인 부탁드립니다

**Comment by min-guk** [comment]
네, 14일 23시 59분 59초까지 제출하시면 됩니다.

Readme에 반영해두겠습니다. 감사합니다.
