### ISSUE TITLE
수행 시간 관련 질문

### ISSUE THREAD

**Issue by lottoian** [DKU-EmbeddedSystem-Lab/2024_DKU_OS#19]
Queue lab2를 구현하고 수행 시간 측정에 관해서 의문점이 있어 issue 올리게 되었습니다.
저번 스케줄링 처럼 unit test를 위해서 test.cpp에서 몇가지를 주석 처리 하면서 생긴 의문점입니다.
궁금한 점은 MultiThreadTest 과정에서 ENQ_THEN_DEQ에서 0번째 case인 thread가 2개일때의 수행속도 시간입니다.

본래 코드에서는 coarse-lock이 먼저 수행되고 fine-grained lock이 수행되는데 제가 fine-grained만 test한다고 coarse lock을 주석으로 처리하고 test를 하니 fine-grained lock 단일 테스트할 때와 coarse lock -> fine grained lock을 수행할때랑 수행속도가 달라진 것을 확인했습니다.
 
![스크린샷 2024-05-12 213806](https://github.com/DKU-EmbeddedSystem-Lab/2024_DKU_OS/assets/67960289/0d3bc877-893d-46c9-ab1b-9729dafe3d5d)
이번 처럼 수행 순서를 바꾼다고 해서  execution time이 차이가 나는 이유를 고민해봐도 모르겠어서 issue 올리게 되었습니다.
감사합니다.

**Comment by min-guk** [comment]
아마 시스템 캐시 영향일 것 같은데요.  여러 번 돌려서 평균 값으로 구하면 아마 일정한 값이 나올 것 같네요.
