### ISSUE TITLE
과제 채점과 관련하여 질문이 있습니다.

### ISSUE THREAD

**Issue by Lagooneng** [DKU-EmbeddedSystem-Lab/2024_DKU_OS#20]
추가된 채점 기준에서 멀티 스레딩 환경에서 Coarse BST가 Fine BST보다 빠르면 감점이라고 되어 있는데,
이게 스레드 수가 같은 경우끼리 비교하는지 궁금합니다.

예를 들어,
Coarse-grained lock의 경우 스레드의 수가 적으면 충돌이 덜 발생해서 스레드의 수가 많을 때보다 성능이 더 좋을 수 있는데, 이로 인해
2스레드의 Coarse BST가 4스레드의 Fine BST보다 조금 빠르게 나온 경우에 감점 대상이 되는지,
아니면 2스레드면 각각 Coarse BST이든 Fine BST이든 
2스레드에 같은 타입인(INSERT_ONLY, INSERT_LOOKUP, INSERT_LOOKUK_DELETE) 것 끼리 비교하는지가 궁금합니다.

감사합니다.

**Comment by min-guk** [comment]
말씀하신대로 같은 워크로드, 같은 스레드 수를 기준으로 fine과 coarse를 비교합니다.
