### ISSUE TITLE
Single에서 질문이 있습니다

### ISSUE THREAD

**Issue by ysoh20** [DKU-EmbeddedSystem-Lab/2024_DKU_OS#21]
![image](https://github.com/DKU-EmbeddedSystem-Lab/2024_DKU_OS/assets/149280122/4fff6696-b682-428e-87b2-9f00800f02cc)

현재 싱글에서 코드를 수행하면 다음과 같은 결과가 나옵니다.
여러번 수행을 하여도 다음과 같이 without lock보다 coarse가 수행시간이 빠르게 나옵니다
멀티 쓰레드 환경에서 fine이 coarse보다 수행시간이 빠르게 나와 정상적인 코드라고 생각이 드는데 다음과 같은 문제가 노트북이나 컴퓨터의 성능에 영향을 받게 되는지 궁금합니다

**Comment by min-guk** [comment]
coarse가 without lock에 단순히 lock만 추가한 것이라면, 코드 레벨에서는 coarse가 without lock보다 느린 것이 당연합니다.  

그렇지 않다라면 이전에 수행한 test, gtest framework, 다른 프로세스 등의 영향으로 시스템에서 간섭이 발생한 것 일수도 있고요. random으로 생성되는 workload의 영향도 있을 수 있겠네요. 

테스트 코드를 수정하여 동일한 테스트를 여러 번 수행한 뒤, 평균을 확인해보면 좋겠네요.
