### ISSUE TITLE
apd의 기능이 궁금합니다.

### ISSUE THREAD

**Issue by toqurqks** [DKU-EmbeddedSystem-Lab/2024_DKU_OS#22]
다른 파일들은 모두 3개의 블럭으로 구성되어있는데 apd를 사용하면 1개의 블럭을 추가하여 4개의 블럭이 되는게 맞나요?

**Comment by min-guk** [comment]
apd는 하나의 블럭을 추가합니다. 파일에 존재하는 모든 블록을 찾으시면 됩니다.
