### ISSUE TITLE
run 함수 관련

### ISSUE THREAD

**Issue by ssng131** [DKU-EmbeddedSystem-Lab/2024_DKU_OS#5]
run함수 결과 작성후 결과가 정확히 답과 같아야 그림과 통계값이 출력되나요?
답과 같지 않아도 제가 작성한 run함수를 바탕으로 그림과 통계값이 출력되나요?

**Comment by min-guk** [comment]
``` cpp
void SchedulerTest::TearDown() {
  // 실행
  run_sched(sched_);
  // 출력
  print_order();
  print_stat();
  // 채점
  check_answer(sched_->get_name(), "stat");
  check_answer(sched_->get_name(), "order");
  delete sched_;
}
```

답과 같지 않아도 학생이 작성한 run함수를 바탕으로 출력됩니다. 하지만 **run함수가 무한 루프, segmentation falut 등으로 종료되지 않는 경우**, 출력함수가 호출되지 않으므로 출력되지 않습니다.

**Comment by ssng131** [comment]
제가 SPN클래스의 run함수 구현 부분에 shced.h에 있는 FCFS 클래스의 run함수 구현을 똑같이 복사 붙여넣기를 해보았는데도, 테스트 시 그림과 통계값이 출력 되지 않습니다.

**Comment by min-guk** [comment]
저희 연구실 ICT관 514호에 오시면, 학생분의 과제 실습 환경을 확인해드리도록 하겠습니다. 
방문 가능한 날짜와 시간대 mgchoi@dankook.ac.kr로 알려주세요

**Comment by min-guk** [comment]
이러한 경우 make clean 후, 다시 make 해보시길 바랍니다.
