### ISSUE TITLE
과제 제출 관련 질문이 있습니다

### ISSUE THREAD

**Issue by Lagooneng** [DKU-EmbeddedSystem-Lab/2024_DKU_OS#6]
<img width="387" alt="osScreen" src="https://github.com/DKU-EmbeddedSystem-Lab/2024_DKU_OS/assets/86322305/a5bb22b8-256f-4ef6-8eb7-fc1d613a1c1b">

과제 파일을 올리면 끝에 [- 이름 ] 과 같이 파일 이름이 자동으로 변형되는데, 이게 맞는 것인지 궁금합니다.

그리고, 저게 잘못된 것인가 헷갈려 응답 수정을 하려는데 응답수정 버튼으로 들어가면 파일은 수정이 안돼서
다른 이메일이 아니라 같은 이메일로 다시 구글 폼 주소로 들어가서 응답수정 버튼을 누르지 않고 재제출하였습니다.

이 경우에 문제가 없는지 궁금합니다.

감사합니다.

**Comment by min-guk** [comment]
네, 제출 후 자동으로 파일명이 변형됩니다.
제출 시에 올바르게 제출하였으니, 걱정하지 않으셔도 됩니다.

**Comment by Lagooneng** [comment]
<img width="363" alt="스크린샷 2024-04-03 오전 9 53 05" src="https://github.com/DKU-EmbeddedSystem-Lab/2024_DKU_OS/assets/86322305/a6b07f7e-a0fa-4de2-bdca-904546a8f2a5">

번거롭게 해드려 죄송하지만, 조금 헷갈려서 한번 더 여쭤봅니다. 위의 응답수정 버튼을 눌러서 응답수정을 한 것이 아니라,

<img width="433" alt="스크린샷 2024-04-03 오전 9 53 59" src="https://github.com/DKU-EmbeddedSystem-Lab/2024_DKU_OS/assets/86322305/4155366d-7bd2-4337-bed1-81c757d54fdb">

위 이미지의 링크를 다시 들어가서 같은 이메일로 재제출을 하였는데 이 경우 괜찮은지 궁금합니다.
응답 수정은 파일이 수정이 되지 않아 이렇게 재제출하였습니다.

**Comment by min-guk** [comment]
말씀해주신대로 구글폼에서는 응답 수정 시에, 파일 수정이 불가하네요. 
학생들이 제출한 마지막 버전으로 채점하겠습니다.
