### ISSUE TITLE
아래 이슈와 마찬가지로 FCFS를 SPN으로 이름만 바꿔서 해보았는데 결과가 나오지 않습니다.

### ISSUE THREAD

**Issue by eagleindesert** [DKU-EmbeddedSystem-Lab/2024_DKU_OS#9]
저도 아래 이슈와 마찬가지로 FCFS를 SPN으로 이름만 바꿔서 해보았는데 결과가 나오지 않습니다. 버추얼머신 없이 wsl로만 하다가 혹시 이게 문제인가 싶어 버츄얼머신으로도 작동시켜 보았는데 해결되지 않았습니다. 몇시간째 위 문제로 헤메고 있어서 질문드립니다..

**Comment by min-guk** [comment]
make clean 후, 다시 make 해보시길 바랍니다.

**Comment by eagleindesert** [comment]
정말 감사합니다. 해결되었습니다!!
